# Generated by Django 5.2.6 on 2025-09-22 05:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('car_inventory', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CarInventory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('car_brand', models.CharField(max_length=20)),
                ('car_model', models.CharField(max_length=20)),
                ('mileage', models.IntegerField()),
                ('engine_type', models.CharField(max_length=20)),
                ('manfg_date', models.DateField()),
            ],
        ),
        migrations.DeleteModel(
            name='car_inventory',
        ),
    ]
